# Generated by Django 4.1 on 2022-08-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRF_Base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.IntegerField()),
                ('img_src', models.CharField(max_length=500)),
                ('notes', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
